### ISSUE TITLE
3.13 support not working on ARM64

### ISSUE THREAD

**Issue by cpeik** [quatrope/scikit-criteria#77]
Hi folks,

We were happy when version 0.9 of `scikit-criteria` was released since [it adds support for Python 3.13](https://github.com/quatrope/scikit-criteria/blob/35f17eeeafd80d666aac740be7c4eba9b14359b8/CHANGELOG.md?plain=1#L45) and [it allows us to use `numpy` 2](https://github.com/quatrope/scikit-criteria/blob/35f17eeeafd80d666aac740be7c4eba9b14359b8/CHANGELOG.md?plain=1#L46).

When I tried to do the Python upgrade for our software component (which uses `scikit-criteria` 0.9) I ran into issues. Building the wheels for matplotlib 3.8.4 with Python 3.13.11 failed on my ARM64 system giveing out the following errors:

```
[...]
      In file included from /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/zlib.h:34:
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/zconf.h:228:12: error: unknown type name 'Byte'
        228 |    typedef Byte  FAR Bytef;
            |            ^
      In file included from /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/ftgzip.c:83:
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/inftrees.h:22:7: error: unknown type name 'Byte'
         22 |       Byte Exop;        /* number of extra bits or operation */
            |       ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/inftrees.h:23:7: error: unknown type name 'Byte'
         23 |       Byte Bits;        /* number of bits in this code or subcode */
            |       ^
      In file included from /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/ftgzip.c:91:
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/inftrees.c:247:21: error: use of undeclared identifier 'Byte'
        247 |           r.bits = (Byte)l;     /* bits to dump before this table */
            |                     ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/inftrees.c:248:21: error: use of undeclared identifier 'Byte'
        248 |           r.exop = (Byte)j;     /* bits in this table */
            |                     ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/inftrees.c:258:17: error: use of undeclared identifier 'Byte'
        258 |       r.bits = (Byte)(k - w);
            |                 ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/inftrees.c:263:19: error: use of undeclared identifier 'Byte'
        263 |         r.exop = (Byte)(*p < 256 ? 0 : 32 + 64);     /* 256 is end-of-block */
            |                   ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/inftrees.c:268:19: error: use of undeclared identifier 'Byte'
        268 |         r.exop = (Byte)(e[*p - s] + 16 + 64);/* non-simple--look up in lists */
            |                   ^
      In file included from /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/ftgzip.c:93:
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/infcodes.c:50:3: error: unknown type name 'Byte'
         50 |   Byte lbits;           /* ltree bits decoded per branch */
            |   ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/infcodes.c:51:3: error: unknown type name 'Byte'
         51 |   Byte dbits;           /* dtree bits decoder per branch */
            |   ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/infcodes.c:70:17: error: use of undeclared identifier 'Byte'
         70 |     c->lbits = (Byte)bl;
            |                 ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/infcodes.c:71:17: error: use of undeclared identifier 'Byte'
         71 |     c->dbits = (Byte)bd;
            |                 ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/infcodes.c:204:9: error: use of undeclared identifier 'Byte'
        204 |         OUTBYTE(*f++)
            |         ^
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/infutil.h:83:27: note: expanded from macro 'OUTBYTE'
         83 | #define OUTBYTE(a) {*q++=(Byte)(a);m--;}
            |                           ^
      In file included from /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/ftgzip.c:93:
      /private/var/folders/5c/msyr8csn64sc3j82f__nr9vh0000gn/T/pip-install-j0rn1kq7/matplotlib_51e2e25e5e514b0a9f601842f70d7f8c/build/freetype-2.6.1/src/gzip/infcodes.c:213:7: error: use of undeclared identifier 'Byte'
        213 |       OUTBYTE(c->sub.lit)
            |       ^
[...]
```

It looks like it is due to [this issue](https://github.com/matplotlib/matplotlib/pull/29247) which got resolved in `matplotlib` 3.10.

Are you sure that `scikit-criteria` does not work with `matplotlib` 3.10? Do you think you might be able to relax the `matplotlib` version requirements? I've just had a quick look and to me it seems that you are mainly using `matplotlib` via `seaborn` which should support `matplotlib` 3.10.

Thank You!

**Comment by leliel12** [comment]
Matplotlib >=3.10 was enabled in commit 85ffc3b860d413b75bc6ff1a4300348fb1f298e6. This change will be included in the next version of scikit-criteria (February 2026).
You can freely install matplotlib 3.10, as all tests pass.

**Comment by cpeik** [comment]
Nice. Thank you! Should I close the issue or will it be closed as soon as the changes are released?

**Comment by manuel-koch** [comment]
@leliel12 Is there a plan for a next release date ? It is now June 2026 and 0.9 is still the latest published scikit-criteria.

**Comment by leliel12** [comment]
The project is almost in feature freeze for the 0.10 release — only two
minor configuration changes are still pending (one of them being Kendall as
the default correlation method). Unfortunately, progress has been slower
than I'd like, as this remains a personal project with limited outside
collaboration. My time is also split across supervising 5 doctoral
students, teaching undergraduate courses, and managing other research lines.

Juan B Cabral
